### ISSUE TITLE
Makefile.dev: No such file or directory

### ISSUE THREAD

**Issue by dubaleeiro** [derekstavis/nrf24le1-libbcm2835#4]
Hello,

after cloning the repository and creating the ../bin folder , command make doesn't work and returns the following message:
`
Makefile:6: Makefile.dev: No such file or directory
make: *** No rule to make target 'Makefile.dev'.  Stop.
`
am I making something wrong? Thanks for your support!

**Comment by derekstavis** [comment]
Closed by #7
